[package]
edition      = "2024"
name         = "c99l_comboard"
rust-version = "1.88"
version      = "0.1.0"

[[bin]]
name = "c99l_comboard"
path = "./src/bin/main.rs"
required-features = ["firmware"]
test = false
bench = false

[[test]]
name = "gnss_setting_response"
path = "./test/gnss_setting_response.rs"
harness = false
required-features = ["hardware-test"]

[features]
default = []
firmware = []
hardware-test = ["firmware"]
lora-timing-debug = []

[target.'cfg(target_arch = "xtensa")'.dependencies]
esp-hal = { version = "1.1.1", features = ["esp32s3", "unstable","log-04"] }

esp-rtos = { version = "0.3.0", features = ["embassy", "esp32s3","log-04"] }

esp-bootloader-esp-idf = { version = "0.5.0", features = ["esp32s3"] }

embassy-executor = { version = "0.10.0", features = [] }
embassy-time = "0.5.0"
esp-backtrace = { version = "0.19.0", features = [
  "esp32s3",
  "panic-handler",
  "println",
] }
esp-println = { version = "0.17.0", features = ["log-04","esp32s3"] }
critical-section = "1.2.0"
static_cell      = "2.1.1"
log = "0.4.33"
nb = "1.1.0"
embedded-can = "0.4.1"
embassy-futures = "0.1.2"
embassy-sync = "0.8.0"
embedded-sdmmc = "0.9.0"
embedded-hal-bus = "0.3.0"
## For time parsing
jiff = { version = "0.2.34", default-features = false, features = ["static"] }
heapless = "0.9.3"


[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units    = 1     # LLVM can perform better optimizations using a single thread
debug            = 2
debug-assertions = false
incremental      = false
lto              = 'fat'
opt-level        = 's'
overflow-checks  = false
